### ISSUE TITLE
bug find when we change speed 

### ISSUE THREAD

**Issue by christie26** [christie26/red-tetris#8]
[meudon] elsikira gameover.
file:///home/yoonsele/project/red-tetris/back/dist/classes/Board.js:219
        for (const tile of this.currentPiece.tiles) {
                                             ^

TypeError: Cannot read properties of null (reading 'tiles')
    at Board.fixPieceToBoard (file:///home/yoonsele/project/red-tetris/back/dist/classes/Board.js:219:46)
    at Board.routine (file:///home/yoonsele/project/red-tetris/back/dist/classes/Board.js:75:18)
    at Timeout._onTimeout (file:///home/yoonsele/project/red-tetris/back/dist/classes/Board.js:113:18)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)

Node.js v20.17.0

**Comment by christie26** [comment]
I change it to be able to set speed only before start a game, only leader can do it
